### PR TITLE
fix: Improve syntax highlighting for enums and annotations.

### PR DESCRIPTION
**Pull request by lukesneeringer**
Fixes some goofy inconsistencies with the existing highlighting, in particular that service/message annotations were highlighted and field annotations were not.

### CODE REVIEW

**Comment by lukesneeringer** [comment]
Screen Shot 2021-05-25 at 9 14 17 AM

**Comment by jgeewax** [comment]
I have no problem whatsoever with the result of the change, but I think the code should have a few more comments (e.g., what each of the conditions represent and why they're there). I suspect that future you/me will be very glad when we have to edit this code.

**Comment by lukesneeringer** [comment]
> I have no problem whatsoever with the result of the change, but I think the code should have a few more comments (e.g., what each of the conditions represent and why they're there). I suspect that future you/me will be very glad when we have to edit this code.

Sounds good. Done.

**Review by jgeewax — APPROVED** [review]

**Comment by keymaster00** [comment]
om om sem sem🔮

**Pull request merged**
